In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [9]:
arr = np.array(l)

In [10]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [11]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [12]:
arr1 = np.array([[1,2,3], [2,3,4]])

In [13]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [14]:
arr[0]=100

In [15]:
arr

array([100,   2,   3,   4,   5])

In [16]:
a=arr

In [17]:
a

array([100,   2,   3,   4,   5])

In [21]:
b=np.copy(arr)

In [22]:
b[0]=656

In [23]:
b

array([656,   2,   3,   4,   5])

In [24]:
arr

array([100,   2,   3,   4,   5])

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
iterable = list(i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('25 36 45', sep=' ')

array([25., 36., 45.])

In [34]:
np.fromstring('25,35, 45', sep=',')

array([25., 35., 45.])

In [35]:
arr.size

5

In [36]:
arr.shape

(5,)

In [37]:
arr.dtype

dtype('int64')

In [38]:
list(range(5))

[0, 1, 2, 3, 4]

In [39]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
np.arange(.4, 10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [43]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [45]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [50]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [52]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [53]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
arr2 = np.eye(5)

In [59]:
import pandas as pd

In [60]:
pd.DataFrame(arr2)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [61]:
np.random.rand(2,3)

array([[0.33442654, 0.84746578, 0.08185866],
       [0.77771749, 0.22561792, 0.40647292]])

In [64]:
np.random.randn(2,3)

array([[-0.78025131,  1.92171322,  0.35623618],
       [-1.35126598, -2.52240048,  0.74723221]])

In [68]:
arr3 = np.random.randint(1,5,(3,4))

In [69]:
arr3.size

12

In [71]:
arr3.reshape(4,3)

array([[3, 4, 1],
       [1, 4, 3],
       [1, 4, 3],
       [4, 2, 4]])

In [72]:
arr3.reshape(6,2)

array([[3, 4],
       [1, 1],
       [4, 3],
       [1, 4],
       [3, 4],
       [2, 4]])

In [74]:
arr3.reshape(3,2,2,1,1)

array([[[[[3]],

         [[4]]],


        [[[1]],

         [[1]]]],



       [[[[4]],

         [[3]]],


        [[[1]],

         [[4]]]],



       [[[[3]],

         [[4]]],


        [[[2]],

         [[4]]]]])

In [75]:
arr3

array([[3, 4, 1, 1],
       [4, 3, 1, 4],
       [3, 4, 2, 4]])

In [77]:
arr4 = np.random.randint(1,10,(5,6))

In [78]:
arr4

array([[7, 5, 1, 7, 6, 6],
       [9, 9, 8, 8, 3, 1],
       [7, 4, 3, 4, 8, 3],
       [5, 6, 5, 1, 8, 3],
       [2, 9, 6, 7, 8, 9]])

In [79]:
arr4>8

array([[False, False, False, False, False, False],
       [ True,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False,  True]])

In [84]:
arr4[arr4>8]

array([9, 9, 9, 9])

In [85]:
arr4[0]

array([7, 5, 1, 7, 6, 6])

In [86]:
arr4[0,[1,2]]

array([5, 1])

In [107]:
arr4[2:4,[3,4]]

array([[4, 8],
       [1, 8]])

In [108]:
arr5 = np.random.randint(1,3,(3,3))
arr6 = np.random.randint(1,3,(3,3))

In [109]:
arr5

array([[2, 2, 1],
       [2, 1, 2],
       [1, 1, 1]])

In [110]:
arr6

array([[1, 2, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [111]:
arr5+arr6

array([[3, 4, 2],
       [3, 2, 3],
       [3, 3, 3]])

In [113]:
np.add(arr5,arr6)

array([[3, 4, 2],
       [3, 2, 3],
       [3, 3, 3]])

In [114]:
arr5-arr6

array([[ 1,  0,  0],
       [ 1,  0,  1],
       [-1, -1, -1]])

In [116]:
np.subtract(arr5,arr6)

array([[ 1,  0,  0],
       [ 1,  0,  1],
       [-1, -1, -1]])

In [117]:
arr5*arr6

array([[2, 4, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [118]:
np.multiply(arr5,arr6)

array([[2, 4, 1],
       [2, 1, 2],
       [2, 2, 2]])

In [119]:
np.mod(arr5,arr6)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [120]:
arr5/arr6

array([[2. , 1. , 1. ],
       [2. , 1. , 2. ],
       [0.5, 0.5, 0.5]])

In [121]:
np.power(arr5,arr6)

array([[2, 4, 1],
       [2, 1, 2],
       [1, 1, 1]])

In [122]:
arr5@arr6

array([[6, 8, 6],
       [7, 9, 7],
       [4, 5, 4]])

In [124]:
arr7 = np.zeros((3,4))

In [125]:
arr7+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [126]:
arr7

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [127]:
a=[1,2,3,4]

In [128]:
arr7+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [138]:
b=np.array([[3,4,5]])

In [139]:
b.T

array([[3],
       [4],
       [5]])

In [141]:
arr8 = arr7+b.T

In [142]:
np.sqrt(arr8)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [143]:
np.max(arr8)

5.0

In [144]:
np.min(arr8)

3.0

In [145]:
np.log10(arr8)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [146]:
np.exp(arr8)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])